version: '3'

services:
  portainer:
    image: portainer/portainer
    ports:
      - "9000"
    networks:
      - {{dockerservice_network}}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  {{dockerservice_network}}:
    external:
      name: {{dockerservice_network}}