version: "3.1"
services:
  redis:
    image: redis:{{redis_version}}
    networks:
      - {{dockerservice_network}}

networks:
  {{dockerservice_network}}:
    external:
      name: {{dockerservice_network}}
