---
- hosts: swarm_manager
  tasks:
  - name: docker info
    command: "docker info --format '{%raw%}{{json .Swarm.Nodes}}'{%endraw%}"
    become: yes
    register: swarm_size
  - name: docker info
    command: "docker info --format '{%raw%}{{json .Swarm.Managers}}'{%endraw%}"
    become: yes
    register: swarm_managers
  - debug:
      var: item
    with_items:
      - "{{swarm_size.stdout}}"
      - "{{swarm_managers.stdout}}"
