---
- name: Install swarm
  become: yes
  become_method: sudo
  hosts: server_swarm
  vars_prompt:
  - name: swarm_name
    prompt: What is the name of your swarm
    private: no
    default: production
  - name: swarm_droplet_size
    prompt: How much ram do you want?
    private: no
    default: 2gb
  roles:
    - role: swarm
      tags: ['install_swarm']
