---
# running this inside droplet causes issues with ssh key
# need to map ssh key from host to container

- name: Create droplet
  hosts:
   - localhost
  vars_prompt:
  - name: swarm_name
    prompt: What is the name of your swarm
    private: no
    default: production
  - name: swarm_droplet_size
    prompt: How much ram do you want?
    private: no
    default: 2gb
  # - name: node_count
  #   prompt: 'How many nodes should be in your swarm'
  #   private: no
  #   default: 3
  vars:
    node_count: 1
    pip_install_packages:
      - name: docker
  pre_tasks:
    - name: Create nodes
      include_role:
        name: swarmnode
      with_sequence: count="{{ node_count | int }}"
      tags: ['provision']

# - name: Refresh inventory
#   hosts:
#     - all
#   tasks:
#     - meta: refresh_inventory

- name: Secure the droplet
  hosts: installing
  gather_facts: false
  pre_tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  roles:
    - role: securenode
      ansible_user: root
      users: "{{ ssh_users }}"
      server_type: "swarm"
    - role: domonitoring
      tags: ['monitoring']
      become: yes

- name: Setup the droplet
  hosts: installing
  pre_tasks:
    - name: Get droplet id
      uri:
        url: http://169.254.169.254/metadata/v1/id
        return_content: yes
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer {{digital_ocean_token}}"
      register: docker_id
      tags: ['swarm', 'cleanup']
  roles:
  - role: geerlingguy.pip
    tags: ['install_docker']
  - role: geerlingguy.docker
    tags: ['install_docker']
  - role: swarm
    become: yes
    tags: ['swarm']
  - role: dosnapshot
    dosnapshot_droplet_id: "{{ docker_id.content|string }}"
    dosnapshot_name: "swarm_snapshot"
    tags: ['swarm', 'cleanup']
    delegate_to: 127.0.0.1
  post_tasks:
    - debug: var=docker_id
      tags: ['swarm', 'cleanup']

    - name: Remove installing tag
      digital_ocean_tag:
        api_token: "{{ digital_ocean_token }}"
        name: "installing"
        resource_id: "{{ docker_id.content|string }}"
        state: absent
      tags: ['swarm', 'cleanup']
      delegate_to: 127.0.0.1

