---
- name: Get droplet id
  uri:
    url: http://169.254.169.254/metadata/v1/id
    headers:
      Content-Type: "application/json"
      Authorization: "Bearer {{digital_ocean_token}}"
  register: docker_id

- debug: var=docker_id