---
- name: Ensure the server has actually booted
  local_action: wait_for host={{ inventory_hostname }} state=started delay=10 timeout=10
  become: false

- include: python.yml

- include: users.yml

- include: harden_ssh.yml

- include: firewall.yml
